In [1]:
import numpy as np

In [ ]:
# create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.dtype)
print(type(arr1))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [11]:
print(arr1.astype('int32'))


[1 2 3 4 5]


In [ ]:
# questions no 1
ans = np.arange(1, 11);
print(ans)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# questions no 2
temp = np.zeros((3,3))
print(temp)
temp1 = np.ones((3,3))
print(temp1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
ans1 = np.arange(2, 21, 2)
print(ans1)

[ 2  4  6  8 10 12 14 16 18 20]


In [16]:
# use of linespace
ans2 = np.linspace(1, 10, 5)
print(ans2)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
arr3 = np.eye(4,4)
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
2
16


In [27]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)
print(arr.dtype)


[1. 2. 3. 4. 5.]
float64
