In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [4]:
temp = np.zeros((3,3))
print(temp)
ans = np.zeros((2,2))
print(ans)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]


In [5]:
p = np.arange(1, 22, 2)
print(p)


[ 1  3  5  7  9 11 13 15 17 19 21]


In [6]:
arr_2_1 = np.arange(12).reshape(3, 4)
print(arr_2_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
np.linspace(10, 50, 7)

array([10.        , 16.66666667, 23.33333333, 30.        , 36.66666667,
       43.33333333, 50.        ])

In [8]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.array([1, 2, 3]) 
np.random.rand(5, 3)

array([[0.85574624, 0.76225108, 0.11976814],
       [0.60513021, 0.82441871, 0.93943641],
       [0.78691148, 0.19892445, 0.25172527],
       [0.96264835, 0.16388129, 0.638856  ],
       [0.10289777, 0.97419495, 0.88229918]])

In [12]:
np.arange(1, 17).reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
arr4 = np.arange(1, 17).reshape(4, 4)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
sub = arr4[:2, 2:]
print(sub)

[[3 4]
 [7 8]]


In [17]:
reversed_both = arr4[::-1, ::-1]
print(reversed_both)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [18]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
np.array([1, 2.5, 3])

array([1. , 2.5, 3. ])

In [21]:
np.array([1.9, 2.5, 3.1])

array([1.9, 2.5, 3.1])

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(a**2)
print(b**2)

[5 7 9]
[ 4 10 18]
[1 4 9]
[16 25 36]


In [25]:
rand_looking = np.array([5, 12, 18, 23, 7, 11, 16, 9, 20, 4])
mask = rand_looking > 15
filtered = rand_looking[mask]
print("Q6.2 filtered >15:", filtered)

Q6.2 filtered >15: [18 23 16 20]


In [27]:
np.random.seed(42)
np.random.rand(3, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [29]:
np.random.randn(5)
np.random.randint(1, 101, 5)


array([80, 15, 62, 62, 47])

In [31]:
mat3 = np.arange(1, 10).reshape(3, 3)
print(np.sum(mat3, axis=0))
print(np.sum(mat3, axis=1))

[12 15 18]
[ 6 15 24]


In [32]:
print("Q8.2 mean:", np.mean(mat3))
print("Q8.2 median:", np.median(mat3))

Q8.2 mean: 5.0
Q8.2 median: 5.0


In [34]:
ones_3x3 = np.ones((3, 3))
vec3 = np.array([1, 2, 3])
print(ones_3x3 + vec3)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [35]:
row_vec = np.array([[1, 2, 3]])        
col_vec = np.array([[4], [5], [6]])  
print(row_vec + col_vec)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [37]:
arr12 = np.arange(12)
reshaped = arr12.reshape(-1, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
vec3 = np.array([1, 2, 3])
vec3[np.newaxis, :]
vec3[:, np.newaxis]


array([[1],
       [2],
       [3]])

In [40]:
arr2d = np.array([[1, 2], [3, 4]])
arr2d.flatten()
arr2d.ravel()

array([1, 2, 3, 4])

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.vstack((A, B))
np.hstack((A, B))
np.concatenate((A, B), axis=0)
np.concatenate((A, B), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
arr6 = np.array([10, 20, 30, 5, 15, 25])
threshold = 15
labels = np.where(arr6 > threshold, 'High', 'Low')
print(labels)

['Low' 'High' 'High' 'Low' 'Low' 'High']


In [47]:
indices = np.where(arr6 > threshold)
print(indices)

(array([1, 2, 5]),)


In [48]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])
M1 * M2
M1 @ M2
np.dot(M1, M2)

array([[19, 22],
       [43, 50]])

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])