In [1]:
import numpy as np

In [ ]:
# question no 1
# syntax of np.arange(start, stop, step)
p = np.arange(1, 20, 2)
print(p)


# question no 2
# syntax of np.linspace(start, stop, num)
arr = np.linspace(5, 45, 9)
print(arr)

# question no 3
a = np.arange(1, 10)
b = np.linspace(1, 9, 9)
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[ 1  3  5  7  9 11 13 15 17 19]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
# question no 4
arr = np.eye(6, dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [5]:
# question no 5
arr = np.full((3, 4), 5)
print(arr)

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
Dimensions: 2


In [6]:
# question no 6
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print("a dtype:", a.dtype)
print("b dtype:", b.dtype)

b = b.astype(int)

print("After conversion:")
print("a dtype:", a.dtype)
print("b dtype:", b.dtype)


a dtype: int64
b dtype: float64
After conversion:
a dtype: int64
b dtype: int64


In [7]:
# question no 7
arr = np.array([10.9, 25.5, 39.99])
result = arr.astype(int)
print(result)

[10 25 39]


In [8]:
# question no 8
arr = np.arange(10, 101, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# question no 9
arr = np.arange(10, 101, 10)
# arr[start:stop]
print(arr[2:6])
# Reverse the complete array
print(arr[::-1])

[30 40 50 60]


In [12]:
# question no 10
arr = np.arange(1, 21)
print(arr[1::3])

[ 2  5  8 11 14 17 20]


In [13]:
# quetsion no 11
arr = np.arange(1, 21)
print(arr[2:-2])


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [14]:
# quetsion no 12
m = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
#  3rd row of the matrix
print(m[2])
# last column of the matrix
print(m[:, -1])
# Centre 3×3 block ---> array[row_slice, column_slice]
print(m[1:4, 1:4])


[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [15]:
# question no 13
print(m[::4, ::4])

[[ 1  5]
 [21 25]]


In [16]:
# question no 14
print(m[::2, ::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [ ]:
# question no 15
# (a) Marks greater than 60
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
result = marks[marks > 60]
print(result)
# (b) Marks between 50 and 80
result1 = marks[(marks >= 50) & (marks <= 80)]
print(result1)


[91 77 62 85 70]
[56 77 62 70]
